In [1]:
import pandas as pd

In [2]:
dataset=pd.read_csv("insurance_pre.csv")

In [3]:
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [4]:
dataset=pd.get_dummies(dataset,drop_first=True)

In [5]:
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400     False        True
1      18  33.770         1   1725.55230      True       False
2      28  33.000         3   4449.46200      True       False
3      33  22.705         0  21984.47061      True       False
4      32  28.880         0   3866.85520      True       False
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830      True       False
1334   18  31.920         0   2205.98080     False       False
1335   18  36.850         0   1629.83350     False       False
1336   21  25.800         0   2007.94500     False       False
1337   61  29.070         0  29141.36030     False        True

[1338 rows x 6 columns]

In [6]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [7]:
indep=dataset[['age', 'bmi', 'children', 'sex_male', 'smoker_yes']]
dep=dataset[['charges']]

In [8]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(indep,dep,test_size=0.30,random_state=0)

In [9]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [10]:
from sklearn.ensemble import RandomForestRegressor

In [19]:
from sklearn.model_selection import GridSearchCV
param_grid = {'criterion':['mse','mae','poisson'],'max_features': ['sqrt','log2'],'n_estimators':[10,50,100]}
grid = GridSearchCV(RandomForestRegressor(), param_grid, refit = True, verbose = 3,n_jobs=-1)
grid.fit(X_train, y_train)

Fitting 5 folds for each of 18 candidates, totalling 90 fits

C:\Users\ANIRUDH\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:425: FitFailedWarning:
60 fits failed out of a total of 90.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
6 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\ANIRUDH\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 732, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\ANIRUDH\anaconda3\Lib\site-packages\sklearn\base.py", line 1144, in wrapper
    estimator._validate_params()
  File "C:\Users\ANIRUDH\anaconda3\Lib\site-packages\sklearn\base.py", line 637, in _validate_params
    validate_parameter_constraints(
  File "C:\Users\ANIRUDH\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'absolute_error', 'friedman_mse', 'squared_error', 'poisson'}. Got 'mse' instead.

--------------------------------------------------------------------------------
6 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\ANIRUDH\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 732, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\ANIRUDH\anaconda3\Lib\site-packages\sklearn\base.py", line 1144, in wrapper
    estimator._validate_params()
  File "C:\Users\ANIRUDH\anaconda3\Lib\site-packages\sklearn\base.py", line 637, in _validate_params
    validate_parameter_constraints(
  File "C:\Users\ANIRUDH\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'absolute_error', 'poisson', 'friedman_mse', 'squared_error'}. Got 'mse' instead.

--------------------------------------------------------------------------------
8 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\ANIRUDH\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 732, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\ANIRUDH\anaconda3\Lib\site-packages\sklearn\base.py", line 1144, in wrapper
    estimator._validate_params()
  File "C:\Users\ANIRUDH\anaconda3\Lib\site-packages\sklearn\base.py", line 637, in _validate_params
    validate_parameter_constraints(
  File "C:\Users\ANIRUDH\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'squared_error', 'poisson', 'absolute_error'}. Got 'mse' instead.

--------------------------------------------------------------------------------
10 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\ANIRUDH\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 732, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\ANIRUDH\anaconda3\Lib\site-packages\sklearn\base.py", line 1144, in wrapper
    estimator._validate_params()
  File "C:\Users\ANIRUDH\anaconda3\Lib\site-packages\sklearn\base.py", line 637, in _validate_params
    validate_parameter_constraints(
  File "C:\Users\ANIRUDH\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'squared_error', 'poisson', 'absolute_error', 'friedman_mse'}. Got 'mse' instead.

--------------------------------------------------------------------------------
10 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\ANIRUDH\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 732, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\ANIRUDH\anaconda3\Lib\site-packages\sklearn\base.py", line 1144, in wrapper
    estimator._validate_params()
  File "C:\Users\ANIRUDH\anaconda3\Lib\site-packages\sklearn\base.py", line 637, in _validate_params
    validate_parameter_constraints(
  File "C:\Users\ANIRUDH\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'squared_error', 'poisson', 'absolute_error'}. Got 'mae' instead.

--------------------------------------------------------------------------------
8 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\ANIRUDH\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 732, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\ANIRUDH\anaconda3\Lib\site-packages\sklearn\base.py", line 1144, in wrapper
    estimator._validate_params()
  File "C:\Users\ANIRUDH\anaconda3\Lib\site-packages\sklearn\base.py", line 637, in _validate_params
    validate_parameter_constraints(
  File "C:\Users\ANIRUDH\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'absolute_error', 'poisson', 'friedman_mse', 'squared_error'}. Got 'mae' instead.

--------------------------------------------------------------------------------
8 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\ANIRUDH\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 732, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\ANIRUDH\anaconda3\Lib\site-packages\sklearn\base.py", line 1144, in wrapper
    estimator._validate_params()
  File "C:\Users\ANIRUDH\anaconda3\Lib\site-packages\sklearn\base.py", line 637, in _validate_params
    validate_parameter_constraints(
  File "C:\Users\ANIRUDH\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'absolute_error', 'friedman_mse', 'squared_error', 'poisson'}. Got 'mae' instead.

--------------------------------------------------------------------------------
4 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\ANIRUDH\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 732, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\ANIRUDH\anaconda3\Lib\site-packages\sklearn\base.py", line 1144, in wrapper
    estimator._validate_params()
  File "C:\Users\ANIRUDH\anaconda3\Lib\site-packages\sklearn\base.py", line 637, in _validate_params
    validate_parameter_constraints(
  File "C:\Users\ANIRUDH\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'squared_error', 'poisson', 'absolute_error', 'friedman_mse'}. Got 'mae' instead.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
C:\Users\ANIRUDH\anaconda3\Lib\site-packages\sklearn\model_selection\_search.py:976: UserWarning: One or more of the test scores are non-finite: [       nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
 0.7939997  0.80982506 0.80994202 0.78896688 0.81062826 0.81240538]
  warnings.warn(
C:\Users\ANIRUDH\anaconda3\Lib\site-packages\sklearn\base.py:1151: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

GridSearchCV(estimator=RandomForestRegressor(), n_jobs=-1,
             param_grid={'criterion': ['mse', 'mae', 'poisson'],
                         'max_features': ['sqrt', 'log2'],
                         'n_estimators': [10, 50, 100]},
             verbose=3)

In [20]:
re=grid.cv_results_

In [21]:
grid_predictions = grid.predict(X_test)

In [22]:
from sklearn.metrics import r2_score
r_score=r2_score(y_test,grid_predictions)

In [23]:
print("The R_score value for best parameter {}:".format(grid.best_params_),r_score)

The R_score value for best parameter {'criterion': 'poisson', 'max_features': 'log2', 'n_estimators': 100}: 0.8687513425521066

In [24]:
table=pd.DataFrame.from_dict(re)

In [25]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_n_estimators,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.002399,0.001853,0.000000,0.000000,mse,sqrt,10,"{'criterion': 'mse', 'max_features': 'sqrt', '...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,7
1,0.001998,0.000632,0.000000,0.000000,mse,sqrt,50,"{'criterion': 'mse', 'max_features': 'sqrt', '...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,7
2,0.002199,0.001468,0.000000,0.000000,mse,sqrt,100,"{'criterion': 'mse', 'max_features': 'sqrt', '...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,7
3,0.002399,0.001356,0.000000,0.000000,mse,log2,10,"{'criterion': 'mse', 'max_features': 'log2', '...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,7
4,0.001599,0.000490,0.000000,0.000000,mse,log2,50,"{'criterion': 'mse', 'max_features': 'log2', '...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,7
5,0.002999,0.001789,0.000000,0.000000,mse,log2,100,"{'criterion': 'mse', 'max_features': 'log2', '...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,7
6,0.001398,0.000798,0.000000,0.000000,mae,sqrt,10,"{'criterion': 'mae', 'max_features': 'sqrt', '...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,7
7,0.001800,0.000749,0.000000,0.000000,mae,sqrt,50,"{'criterion': 'mae', 'max_features': 'sqrt', '...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,7
8,0.001600,0.000490,0.000000,0.000000,mae,sqrt,100,"{'criterion': 'mae', 'max_features': 'sqrt', '...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,7
9,0.001599,0.000491,0.000000,0.000000,mae,log2,10,"{'criterion': 'mae', 'max_features': 'log2', '...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,7
10,0.001000,0.000003,0.000000,0.000000,mae,log2,50,"{'criterion': 'mae', 'max_features': 'log2', '...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,7
11,0.003199,0.001938,0.000000,0.000000,mae,log2,100,"{'criterion': 'mae', 'max_features': 'log2', '...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,7
12,0.118126,0.016341,0.008195,0.000748,poisson,sqrt,10,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.845821,0.779883,0.794478,0.796893,0.752924,0.794000,0.030267,5
13,0.493101,0.007628,0.019789,0.004065,poisson,sqrt,50,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.860910,0.786278,0.802875,0.832261,0.766802,0.809825,0.033367,4
14,0.879867,0.125575,0.028187,0.005413,poisson,sqrt,100,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.863022,0.782205,0.806617,0.825299,0.772567,0.809942,0.032344,3
15,0.088771,0.005907,0.006599,0.001354,poisson,log2,10,"{'criterion': 'poisson', 'max_features': 'log2...",0.830146,0.756892,0.801627,0.806107,0.750062,0.788967,0.030634,6
16,0.495297,0.009326,0.020787,0.000979,poisson,log2,50,"{'criterion': 'poisson', 'max_features': 'log2...",0.863205,0.790234,0.801979,0.829343,0.768380,0.810628,0.032834,2
17,0.825416,0.156959,0.029188,0.006331,poisson,log2,100,"{'criterion': 'poisson', 'max_features': 'log2...",0.867606,0.797272,0.803693,0.825807,0.767650,0.812405,0.033271,1

In [26]:
age_input=float(input("Age:"))
bmi_input=float(input("BMI:"))
children_input=float(input("Children:"))
sex_male_input=int(input("Sex Male 0 or 1:"))
smoker_yes_input=int(input("Smoker Yes 0 or 1:"))

Age:36
BMI:160
Children:2
Sex Male 0 or 1:0
Smoker Yes 0 or 1:0

In [28]:
Future_Prediction=grid.predict([[age_input,bmi_input,children_input,sex_male_input,smoker_yes_input]])

In [29]:
print("Future_Prediction={}".format(Future_Prediction))

Future_Prediction=[14831.3594335]